// packages/vue/src/PlacesAutocomplete.tsx
import { defineComponent, onMounted, onUnmounted, ref, useId, watch } from 'vue'
import type { PropType } from 'vue'
import { usePlacesAutocomplete } from './usePlacesAutocomplete'
import { bindOutsideClose } from '@anil-labs/google-places-autocomplete-core'
import type {
  Fetcher,
  LocationBias,
  PlaceDetails,
  PlacesAutocompleteError,
  Suggestion,
} from '@anil-labs/google-places-autocomplete-core'

export const PlacesAutocomplete = defineComponent({
  name: 'PlacesAutocomplete',
  props: {
    modelValue: { type: String, default: '' },
    placeholder: { type: String, default: 'Search for an address…' },
    apiKey: { type: String, default: undefined },
    fetcher: { type: Function as PropType<Fetcher>, default: undefined },
    debounceMs: { type: Number, default: undefined },
    minLength: { type: Number, default: undefined },
    languageCode: { type: String, default: undefined },
    regionCode: { type: String, default: undefined },
    includedRegionCodes: { type: Array as PropType<string[]>, default: undefined },
    locationBias: { type: Object as PropType<LocationBias>, default: undefined },
    resolveDetails: { type: Boolean, default: undefined },
  },
  emits: {
    'update:modelValue': (_value: string) => true,
    select: (_place: PlaceDetails, _suggestion: Suggestion) => true,
    error: (_error: PlacesAutocompleteError) => true,
  },
  setup(props, { emit }) {
    const uid = useId()
    const rootRef = ref<HTMLDivElement | null>(null)
    const { state, controller } = usePlacesAutocomplete({
      apiKey: props.apiKey,
      fetcher: props.fetcher,
      debounceMs: props.debounceMs,
      minLength: props.minLength,
      languageCode: props.languageCode,
      regionCode: props.regionCode,
      includedRegionCodes: props.includedRegionCodes,
      locationBias: props.locationBias,
      resolveDetails: props.resolveDetails,
      onSelect: (place, suggestion) => emit('select', place, suggestion),
      onError: (error) => emit('error', error),
    })

    if (props.modelValue) controller.setQuery(props.modelValue)

    // Lets a parent reset the field (e.g. on form submit) by writing to the
    // v-model value; feedback loops are avoided by only reacting when the
    // incoming value differs from what the machine already has.
    watch(
      () => props.modelValue,
      (next) => {
        if (next !== state.value.query) controller.setQuery(next)
      },
    )

    let unbindOutsideClose: (() => void) | null = null
    onMounted(() => {
      if (rootRef.value) {
        unbindOutsideClose = bindOutsideClose(rootRef.value, () => controller.close())
      }
    })
    onUnmounted(() => unbindOutsideClose?.())

    function handleInput(event: Event): void {
      const value = (event.target as HTMLInputElement).value
      emit('update:modelValue', value)
      controller.setQuery(value)
    }

    function handleKeydown(event: KeyboardEvent): void {
      switch (event.key) {
        case 'ArrowDown':
          event.preventDefault()
          controller.moveActive(1)
          break
        case 'ArrowUp':
          event.preventDefault()
          controller.moveActive(-1)
          break
        case 'Enter':
          if (state.value.isOpen) {
            event.preventDefault()
            controller.selectActive()
          }
          break
        case 'Escape':
          controller.close()
          break
      }
    }

    return () => {
      const current = state.value
      return (
        <div class="gpa-root" ref={rootRef}>
          <input
            class="gpa-input"
            type="text"
            role="combobox"
            aria-expanded={current.isOpen}
            aria-autocomplete="list"
            aria-controls={`${uid}-panel`}
            aria-activedescendant={
              current.isOpen && current.activeIndex >= 0
                ? `${uid}-option-${current.activeIndex}`
                : undefined
            }
            autocomplete="off"
            placeholder={props.placeholder}
            value={current.query}
            onInput={handleInput}
            onKeydown={handleKeydown}
          />
          {current.isOpen && (
            <div class="gpa-panel" id={`${uid}-panel`}>
              {current.status === 'loading' ? (
                <div class="gpa-status" role="status">
                  Searching…
                </div>
              ) : current.suggestions.length === 0 ? (
                <div class="gpa-empty" role="status">
                  No results found
                </div>
              ) : (
                <ul class="gpa-listbox" role="listbox">
                  {current.suggestions.map((suggestion, index) => (
                    <li
                      key={suggestion.placeId}
                      id={`${uid}-option-${index}`}
                      class="gpa-option"
                      role="option"
                      aria-selected={index === current.activeIndex}
                      data-active={index === current.activeIndex}
                      onMousedown={(event: MouseEvent) => {
                        event.preventDefault()
                        controller.selectSuggestion(suggestion)
                      }}
                    >
                      <div class="gpa-option-main">{suggestion.mainText}</div>
                      {suggestion.secondaryText && (
                        <div class="gpa-option-secondary">{suggestion.secondaryText}</div>
                      )}
                    </li>
                  ))}
                </ul>
              )}
            </div>
          )}
        </div>
      )
    }
  },
})

// packages/react/src/PlacesAutocomplete.tsx
import { forwardRef, useEffect, useId, useRef } from 'react'
import type { ChangeEvent, KeyboardEvent } from 'react'
import { usePlacesAutocomplete } from './usePlacesAutocomplete'
import {
  bindOutsideClose,
  type PlacesAutocompleteConfig,
} from '@anil-labs/google-places-autocomplete-core'

export interface PlacesAutocompleteProps extends Omit<
  PlacesAutocompleteConfig,
  'onSelect' | 'onError'
> {
  /** Controlled input value. Omit for uncontrolled usage driven entirely by the machine's own query state. */
  value?: string
  onValueChange?: (value: string) => void
  onSelect?: PlacesAutocompleteConfig['onSelect']
  onError?: PlacesAutocompleteConfig['onError']
  placeholder?: string
  className?: string
}

export const PlacesAutocomplete = forwardRef<HTMLInputElement, PlacesAutocompleteProps>(
  function PlacesAutocomplete(
    {
      value,
      onValueChange,
      onSelect,
      onError,
      placeholder = 'Search for an address…',
      className,
      ...config
    },
    ref,
  ) {
    const uid = useId()
    const rootRef = useRef<HTMLDivElement>(null)
    const { state, controller } = usePlacesAutocomplete({ ...config, onSelect, onError })

    // Lets a parent reset the field (e.g. on form submit) by writing to
    // `value`; the guard avoids re-issuing setQuery for a no-op change.
    useEffect(() => {
      if (value !== undefined && value !== state.query) controller.setQuery(value)
    }, [value, state.query, controller])

    useEffect(() => {
      if (!rootRef.current) return
      return bindOutsideClose(rootRef.current, () => controller.close())
    }, [controller])

    function handleChange(event: ChangeEvent<HTMLInputElement>): void {
      const next = event.target.value
      onValueChange?.(next)
      controller.setQuery(next)
    }

    function handleKeyDown(event: KeyboardEvent<HTMLInputElement>): void {
      switch (event.key) {
        case 'ArrowDown':
          event.preventDefault()
          controller.moveActive(1)
          break
        case 'ArrowUp':
          event.preventDefault()
          controller.moveActive(-1)
          break
        case 'Enter':
          if (state.isOpen) {
            event.preventDefault()
            controller.selectActive()
          }
          break
        case 'Escape':
          controller.close()
          break
      }
    }

    return (
      <div className={['gpa-root', className].filter(Boolean).join(' ')} ref={rootRef}>
        <input
          ref={ref}
          className="gpa-input"
          type="text"
          role="combobox"
          aria-expanded={state.isOpen}
          aria-autocomplete="list"
          aria-controls={`${uid}-panel`}
          aria-activedescendant={
            state.isOpen && state.activeIndex >= 0
              ? `${uid}-option-${state.activeIndex}`
              : undefined
          }
          autoComplete="off"
          placeholder={placeholder}
          value={state.query}
          onChange={handleChange}
          onKeyDown={handleKeyDown}
        />
        {state.isOpen && (
          <div className="gpa-panel" id={`${uid}-panel`}>
            {state.status === 'loading' ? (
              <div className="gpa-status" role="status">
                Searching…
              </div>
            ) : state.suggestions.length === 0 ? (
              <div className="gpa-empty" role="status">
                No results found
              </div>
            ) : (
              <ul className="gpa-listbox" role="listbox">
                {state.suggestions.map((suggestion, index) => (
                  <li
                    key={suggestion.placeId}
                    id={`${uid}-option-${index}`}
                    className="gpa-option"
                    role="option"
                    aria-selected={index === state.activeIndex}
                    data-active={index === state.activeIndex}
                    onMouseDown={(event) => {
                      event.preventDefault()
                      controller.selectSuggestion(suggestion)
                    }}
                  >
                    <div className="gpa-option-main">{suggestion.mainText}</div>
                    {suggestion.secondaryText && (
                      <div className="gpa-option-secondary">{suggestion.secondaryText}</div>
                    )}
                  </li>
                ))}
              </ul>
            )}
          </div>
        )}
      </div>
    )
  },
)
